import { google } from "googleapis";
type Config={clientId:string;clientSecret:string;redirectUri:string}; let runtime:Config|null=null; let tokens:any=null; let oauthState="";
const scopes=["openid","email","profile","https://www.googleapis.com/auth/gmail.readonly","https://www.googleapis.com/auth/gmail.send","https://www.googleapis.com/auth/gmail.modify","https://www.googleapis.com/auth/calendar"];
export function configureGoogleOAuth(clientId:string,clientSecret:string,redirectUri:string){runtime={clientId:clientId.trim(),clientSecret:clientSecret.trim(),redirectUri};tokens=null;}
export function getGoogleOAuthConfig(){const clientId=runtime?.clientId||process.env.GOOGLE_CLIENT_ID?.trim();const clientSecret=runtime?.clientSecret||process.env.GOOGLE_CLIENT_SECRET?.trim();const redirectUri=runtime?.redirectUri||process.env.GOOGLE_OAUTH_REDIRECT_URI?.trim()||"http://127.0.0.1:8787/api/google/oauth/callback";return clientId&&clientSecret?{clientId,clientSecret,redirectUri}:null;}
function client(){const c=getGoogleOAuthConfig();if(!c)throw new Error("Google OAuth is not configured.");return new google.auth.OAuth2(c.clientId,c.clientSecret,c.redirectUri);}
export function getGoogleOAuthUrl(){const c=client();oauthState=crypto.randomUUID();return c.generateAuthUrl({access_type:"offline",prompt:"consent",scope:scopes,state:oauthState});}
export async function finishGoogleOAuth(code:string,state:string){if(!state||state!==oauthState)throw new Error("Google OAuth state validation failed.");const c=client();tokens=(await c.getToken(code)).tokens;}
export function isGoogleConnected(){return Boolean(tokens?.access_token||tokens?.refresh_token);}
async function auth(){if(!isGoogleConnected())throw new Error("Google is not connected. Connect Google in EFITH Settings.");const c=client();c.setCredentials(tokens);if(tokens.expiry_date&&tokens.expiry_date<Date.now()+60000){const r=await c.getAccessToken();if(r.token)tokens={...tokens,access_token:r.token};}c.on("tokens",t=>tokens={...tokens,...t});return c;}
function confirm(a:Record<string,unknown>){if(a.confirm!==true)throw new Error("Confirmation required. Ask the user to confirm this exact action, then call again with confirm=true.");}
export async function runGoogleTool(name:string,a:Record<string,unknown>){const c=await auth();
if(name==="gmail_search"){const g=google.gmail({version:"v1",auth:c});const r=await g.users.messages.list({userId:"me",q:String(a.query||""),maxResults:Math.min(Number(a.maxResults||10),50)});const out=[];for(const m of r.data.messages||[]){const d=await g.users.messages.get({userId:"me",id:m.id!,format:"metadata",metadataHeaders:["From","To","Subject","Date"]});const h=Object.fromEntries((d.data.payload?.headers||[]).map(x=>[x.name||"",x.value||""]));out.push({id:m.id,threadId:m.threadId,snippet:d.data.snippet,...h});}return {messages:out};}
if(name==="gmail_get"){const g=google.gmail({version:"v1",auth:c});const r=await g.users.messages.get({userId:"me",id:String(a.messageId),format:"full"});return {id:r.data.id,threadId:r.data.threadId,snippet:r.data.snippet,headers:r.data.payload?.headers,body:r.data.payload};}
if(name==="gmail_send"){confirm(a);const g=google.gmail({version:"v1",auth:c});const raw=Buffer.from("To: "+a.to+"\r\nSubject: "+a.subject+"\r\nContent-Type: text/plain; charset=\"UTF-8\"\r\n\r\n"+a.body).toString("base64url");const r=await g.users.messages.send({userId:"me",requestBody:{raw}});return {sent:true,id:r.data.id,threadId:r.data.threadId};}
if(name==="gmail_trash"){confirm(a);const g=google.gmail({version:"v1",auth:c});await g.users.messages.trash({userId:"me",id:String(a.messageId)});return {trashed:true,id:String(a.messageId)};}
if(name==="calendar_list"){const g=google.calendar({version:"v3",auth:c});const r=await g.events.list({calendarId:"primary",timeMin:String(a.timeMin||new Date().toISOString()),timeMax:a.timeMax?String(a.timeMax):undefined,singleEvents:true,orderBy:"startTime",maxResults:Math.min(Number(a.maxResults||20),100)});return (r.data.items||[]).map(e=>({id:e.id,summary:e.summary,start:e.start,end:e.end,location:e.location,description:e.description,htmlLink:e.htmlLink}));}
if(name==="calendar_create"){confirm(a);const g=google.calendar({version:"v3",auth:c});const r=await g.events.insert({calendarId:"primary",requestBody:{summary:String(a.summary),description:a.description?String(a.description):undefined,location:a.location?String(a.location):undefined,start:{dateTime:String(a.startDateTime),timeZone:a.timeZone?String(a.timeZone):undefined},end:{dateTime:String(a.endDateTime),timeZone:a.timeZone?String(a.timeZone):undefined},attendees:Array.isArray(a.attendees)?a.attendees.map(x=>({email:String(x)})):undefined}});return {created:true,id:r.data.id,htmlLink:r.data.htmlLink};}
if(name==="calendar_update"){confirm(a);const g=google.calendar({version:"v3",auth:c});const id=String(a.eventId);const old=(await g.events.get({calendarId:"primary",eventId:id})).data;const r=await g.events.update({calendarId:"primary",eventId:id,requestBody:{...old,...(a.summary!==undefined?{summary:String(a.summary)}:{}),...(a.description!==undefined?{description:String(a.description)}:{}),...(a.startDateTime!==undefined?{start:{...old.start,dateTime:String(a.startDateTime)}}:{}),...(a.endDateTime!==undefined?{end:{...old.end,dateTime:String(a.endDateTime)}}:{})}});return {updated:true,id:r.data.id,htmlLink:r.data.htmlLink};}
if(name==="calendar_delete"){confirm(a);const g=google.calendar({version:"v3",auth:c});const id=String(a.eventId);await g.events.delete({calendarId:"primary",eventId:id});return {deleted:true,id};}
throw new Error("Unknown Google tool: "+name);}
export const GOOGLE_TOOLS=[{name:"gmail_search",description:"Search the user's Gmail. Read-only.",parameters:{type:"object",properties:{query:{type:"string"},maxResults:{type:"integer"}},required:["query"],additionalProperties:false}},{name:"gmail_get",description:"Read a Gmail message. Read-only.",parameters:{type:"object",properties:{messageId:{type:"string"}},required:["messageId"],additionalProperties:false}},{name:"gmail_send",description:"Send an email. Ask for explicit confirmation immediately before sending, then use confirm=true.",parameters:{type:"object",properties:{to:{type:"string"},subject:{type:"string"},body:{type:"string"},confirm:{type:"boolean"}},required:["to","subject","body","confirm"],additionalProperties:false}},{name:"gmail_trash",description:"Move an email to trash. Ask for explicit confirmation first.",parameters:{type:"object",properties:{messageId:{type:"string"},confirm:{type:"boolean"}},required:["messageId","confirm"],additionalProperties:false}},{name:"calendar_list",description:"List primary Google Calendar events. Read-only.",parameters:{type:"object",properties:{timeMin:{type:"string"},timeMax:{type:"string"},maxResults:{type:"integer"}},additionalProperties:false}},{name:"calendar_create",description:"Create a calendar event. Ask for explicit confirmation immediately before creating it.",parameters:{type:"object",properties:{summary:{type:"string"},description:{type:"string"},location:{type:"string"},startDateTime:{type:"string"},endDateTime:{type:"string"},timeZone:{type:"string"},attendees:{type:"array",items:{type:"string"}},confirm:{type:"boolean"}},required:["summary","startDateTime","endDateTime","confirm"],additionalProperties:false}},{name:"calendar_update",description:"Update a calendar event. Ask for explicit confirmation first.",parameters:{type:"object",properties:{eventId:{type:"string"},summary:{type:"string"},description:{type:"string"},startDateTime:{type:"string"},endDateTime:{type:"string"},confirm:{type:"boolean"}},required:["eventId","confirm"],additionalProperties:false}},{name:"calendar_delete",description:"Delete a calendar event. Ask for explicit confirmation first.",parameters:{type:"object",properties:{eventId:{type:"string"},confirm:{type:"boolean"}},required:["eventId","confirm"],additionalProperties:false}}] as const;